### PR TITLE
First attempt for a run script for windows

### PR DESCRIPTION
**Pull request by zuphilip**

### CODE REVIEW

**Comment by kba** [comment]
Have a look at https://docs.docker.com/compose/compose-file/#variable-substitution . If this is to be run from a POSIX shell like bash, we could change the volume mounts to some thing like

``` yaml
volume:
  '${PWD}/translators:/opt/zts/modules/translators'
```

and it Should Just Work(TM) because `$PWD` is always exported by the shell.

**Comment by kba** [comment]
Unfortunately that won't allow default values, so it's not at the moment an option for the `localhost` vs. docker-machine IP problem, c.f. https://github.com/docker/compose/issues/2441

**Comment by kba** [comment]
While it's great that docker-compose is such a popular and fast-moving project, finding the current status of some features takes a while.

Turns out this is possible with a `.env` file already: https://docs.docker.com/compose/env-file/.

<del>It's also very possible that `DOCKER_HOST` is injected anyway but need to test some more.</del>

**Comment by zuphilip** [comment]
Thanks. It is good to know that `{PWD}` will already work in `docker-compose.yml`.

My idea is to have some solution, which allows synchronizing all files through git, but to have a simple command call under linux and windows. This can be done with this special script for win (which I corrected now, credit to http://stackoverflow.com/questions/29061026/using-the-host-ip-in-docker-compose) but I don't see that it can be also achieved with env-files (but maybe I just don't understand that completely).

**Comment by kba** [comment]
https://github.com/kba/zts-in-a-box/pull/3

It's a balancing act between having a completely clean Git repository, i.e. no changes needed to files saved in any file comitted to git and complexity of setup, e.g. the environment, not files, influencing the setup, which makes debugging harder.

I think that using a `.env` can be a good solution here: Linux/Win10 users won't have to change anything, Win 7/8/OSX users should run a script whenever their docker machine's IP changes but it's persisted to `.env`, so if something breaks, it's because of the settings here.

Only have to make sure not to check in `.env` after changing `ZTS_HOST` but I think that is possible.

**Comment by kba** [comment]
#3 implements this.

**Pull request closed without merging**
